#!/bin/sh
# /usr/lib/xymon/client/ext/rblcheck

# /etc/xymon/clientlaunch.d/rblcheck.cfg
#[rblcheck]
#	DISABLED
#	ENVFILE /etc/xymon/xymonclient.cfg
#	CMD $XYMONCLIENTHOME/ext/rblcheck
#	LOGFILE /var/log/xymon/xymonclient.log
#	INTERVAL 4h
#	LIFETIME 8h

COLUMN=rblcheck
COLOR=green
MSG="<b>rblcheck status</b><br>"
rm -f /tmp/rblcheckfound.lst

DNSBLlist=`grep -v ^# <<!
all.spamrats.com
b.barracudacentral.org
bl.blocklist.de
bl.spamcop.net
bl.spameatingmonkey.net
dnsbl.sorbs.net
sbl-xbl.spamhaus.org
sbl.spamhaus.org
xbl.spamhaus.org
zen.spamhaus.org
!`

# Put in here the IP servers to check.
MSERVIPS=`grep -v ^# <<!
1.2.3.4
!`

 for i in $DNSBLlist
 do
 for e in $MSERVIPS
 do
 IP=`echo $e | awk 'BEGIN { FS = "." } ; { print $4 "." $3 "." $2 "."$1 }'`
 if dig $IP.$i +short | grep -q "^127.0.0."
 then
 echo "$e found on $i" >> /tmp/rblcheckfound.lst
 MSG2=`cat /tmp/rblcheckfound.lst`
 COLOR=red
 fi
 done
 done

# Send the results to hobbit so it can be graphed.
$BB $BBDISP "status $MACHINE.$COLUMN $COLOR `date`

${MSG}
${MSG2}
"

exit 0